### ISSUE TITLE
Component .js files not generating correctly on Windows due to backslashes

### ISSUE THREAD

**Issue by nirslsk** [GIVESocialMovement/sbt-vuefy#13] opened 2018-08-01 02:56 UTC
There may be an issue generating component .js files when building on Windows. I have a component named LinkViews.vue that generates a corresponding link-views.js. On Windows, I get this error in Chrome: "Uncaught SyntaxError: Invalid or unexpected token" relating to line 1 in link-views.js, which looks like this:

```
var Vue\components\linkViews =
```

Comparatively, on MacOS or Linux there is no error. The line looks like this:

```
var LinkViews =
```

Seems related to the fact Windows uses backslashes instead of slashes. Let me know if you don't have access to a Windows machine and need me to test a possible fix.

Thanks, Nir

**Comment by tanin47** [comment] 2018-08-01 15:18
I haven't tested on Windows at all. In many places, `/` is used for joining paths. But this should be fixable. Let me explore it a bit.

**Comment by tanin47** [comment] 2018-08-02 02:05
Here's the root cause: `let tokens = data.chunk.name.split('/');` at https://github.com/GIVESocialMovement/sbt-vuefy/blob/69c161d3be40fef93d618be18136bef10cba0549/src/main/resources/sbt-vuefy-plugin.js#L9

**Comment by tanin47** [comment] 2018-08-02 02:09
@nirslsk if you can help test on Windows, that would be great. Here's the instruction:

1. Clone this repo
2. Go to the folder `test-play-project`
3. `sbt run` and go to `http://localhost:9000`

Please let me know if it works. Thank you!

**Comment by tanin47** [comment] 2018-08-02 03:33
@nirslsk I've just updated the branch with tests. 

Could you also try `sbt test` on the root folder to see if the unit tests pass. 

Thank you very much for your help.

**Comment by nirslsk** [comment] 2018-08-02 03:54
Sure thing! I'm not seeing any additional commits in the `fix-windows` branch, but `sbt test` does pass:

![sbt-test](https://user-images.githubusercontent.com/2808762/43561701-0b1f759a-95cd-11e8-9573-ff5b935ecfbb.png)

Are the tests not checked in?

**Comment by tanin47** [comment] 2018-08-02 03:55
Sorry, I just merged it to `master` because I was somewhat sure it would work.

`sbt test` should be run on the root folder (not in the test-play-folder).

**Comment by tanin47** [comment] 2018-08-02 04:26
This seems trickier than I thought. I might need to test the plugin on windows myself. 

In the meantime, you can use the new version `1.1.0` for the window support.

Thank you again.

**Comment by nirslsk** [comment] 2018-08-02 04:29
Sounds good. Thank you!

**Comment by tanin47** [comment] 2018-08-02 05:37
The root cause is that `webpack`, even on windows, uses `/` (not `\`). 

We are reading the dependency from Webpack's artifact, and those artifacts use `/`.

The fix is coming.

**Comment by tanin47** [comment] 2018-08-02 05:46
The impact is that hot-reloading wouldn't work properly because we didn't detect dependencies correctly.

**Closed** 2018-08-02 06:00 UTC
Labels: bug

**Comment by tanin47** [comment] 2018-08-02 06:01
@nirslsk Please upgrade to 1.2.0

Thank you for using sbt-vuefy and for reporting this issue!

**Comment by nirslsk** [comment] 2018-08-02 06:59
Everything works, including the tests and my project! Thank you Tanin.
